### ISSUE TITLE
ClientReference.md文件中的一个小问题~

### ISSUE THREAD

**Issue by OneGIl** [HuberTRoy/aiohttp-chinese-document#1]
第22行`loop.run_until_complete(main(loop))`这段中，main函数是不需要loop这个参数的。如果带参数是无法运行并会报错。而且也确认过官方文档中的代码，也是没有这个参数的。

然后，感谢你的翻译~

**Comment by HuberTRoy** [comment]
@OneGIl 
感谢，已更正~。
